# Generated by Django 4.1.7 on 2023-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_delete_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
