# Generated by Django 4.1.7 on 2023-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='process',
            field=models.IntegerField(),
        ),
    ]
