# Generated by Django 4.1.7 on 2023-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_notes_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='process',
            field=models.CharField(max_length=1),
        ),
    ]
