# Generated by Django 4.1.7 on 2023-03-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_commentary_executor_notes_executor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='executor',
            new_name='commentator',
        ),
    ]
