# Generated by Django 4.1.7 on 2023-03-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_rename_executor_commentary_commentator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='process',
            new_name='status',
        ),
    ]
