# Generated by Django 4.1.7 on 2023-03-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_rename_process_notes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='dateoflsu',
            field=models.DateTimeField(null=True),
        ),
    ]
