# Generated by Django 4.1.7 on 2023-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_notes_dateoflsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='commentator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='dateoflsu',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='executor',
            field=models.CharField(max_length=100),
        ),
    ]
