# Generated by Django 4.1.7 on 2023-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_commentary_commentator_alter_notes_dateoflsu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='pk_note',
            field=models.IntegerField(null=True),
        ),
    ]
