# Generated by Django 4.1.7 on 2023-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_commentary_pk_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='pk_note',
            field=models.IntegerField(),
        ),
    ]
